//
// Channel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Channel: Codable {

    public var orderNum: Int?
    public var accessNum: Int?
    public var callSign: String?
    public var _id: Int?

    public init(orderNum: Int? = nil, accessNum: Int? = nil, callSign: String? = nil, _id: Int? = nil) {
        self.orderNum = orderNum
        self.accessNum = accessNum
        self.callSign = callSign
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case orderNum
        case accessNum
        case callSign = "CallSign"
        case _id = "id"
    }

}
