//
// ChannelsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ChannelsAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func channelsGet(completion: @escaping ((_ data: [Channel]?,_ error: Error?) -> Void)) {
        channelsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /Channels
     - 

     - examples: [{contentType=application/json, example=[ {
  "CallSign" : "ASDM",
  "orderNum" : 10,
  "id" : 302746,
  "accessNum" : 198772
}, {
  "CallSign" : "ASDM",
  "orderNum" : 10,
  "id" : 302746,
  "accessNum" : 198772
} ]}]

     - returns: RequestBuilder<[Channel]> 
     */
    open class func channelsGetWithRequestBuilder() -> RequestBuilder<[Channel]> {
        let path = "/Channels"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Channel]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
